name: pylabianca
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py>=3.10.0
  - hdf5
  - matplotlib>=3.8.0
  - mkl
  - numpy>=1.26.4
  - numpydoc
  - pandas>=2.1.2
  - pip
  - scikit-learn>=1.3.2
  - scikit-image
  - scipy>=1.11.3
  - setuptools
  - tqdm>=4.66.1
  - xarray>=2023.10.1
  - xlrd>=2.0.1
  - pip:
    - "--no-deps borsar"
    - elephant
    - h5io>=0.1.9
    - h5netcdf
    - neo
    - quantities
    - statsmodels
